#!/bin/sh

# Just like https://github.com/eficode/wait-for/raw/master/wait-for, but
# using more conventional lower-case for local variables (mostly so that
# PORT doesn't get exported into whatever is being exec'd).

timeout=15
quiet=0
cmdname=$(basename $0)

echoerr() {
  if [ "$quiet" -ne 1 ]; then printf "%s\n" "$*" 1>&2; fi
}

usage() {
  exitcode="$1"
  cat << USAGE >&2
Usage:
  $cmdname host:port [-t timeout] [-- command args]
  -q | --quiet                        Do not output any status messages
  -t TIMEOUT | --timeout=timeout      Timeout in seconds, zero for no timeout
  -- COMMAND ARGS                     Execute command with args after the test finishes
USAGE
  exit "$exitcode"
}

wait_for() {
  for i in `seq $timeout` ; do
    nc -z "$host" "$port" > /dev/null 2>&1
    
    result=$?
    if [ $result -eq 0 ] ; then
      if [ $# -gt 0 ] ; then
        exec "$@"
      fi
      exit 0
    fi
    sleep 1
  done
  echo "Operation timed out" >&2
  exit 1
}

while [ $# -gt 0 ]
do
  case "$1" in
    *:* )
    host=$(printf "%s\n" "$1"| cut -d : -f 1)
    port=$(printf "%s\n" "$1"| cut -d : -f 2)
    shift 1
    ;;
    -q | --quiet)
    quiet=1
    shift 1
    ;;
    -t)
    timeout="$2"
    if [ "$timeout" = "" ]; then break; fi
    shift 2
    ;;
    --timeout=*)
    timeout="${1#*=}"
    shift 1
    ;;
    --)
    shift
    break
    ;;
    --help)
    usage 0
    ;;
    *)
    echoerr "Unknown argument: $1"
    usage 1
    ;;
  esac
done

if [ "$host" = "" -o "$port" = "" ]; then
  echoerr "Error: you need to provide a host and port to test."
  usage 2
fi

wait_for "$@"
